config:

logo:
  nav_mobile: '../images/logo-coralspace.svg'
  sidebar: '../images/icon-white.svg'

nav_links:
  'Tutorials':
    url: http://tutorials.meteor.com
    partial: illustration-guide
  'Guide':
    url: http://guide.meteor.com
    partial: illustration-compass
  'Docs':
    url: http://docs.meteor.com
    partial: illustration-logs
  'Forums':
    url: https://forums.meteor.com/
    partial: illustration-support

social_links:
  github: 'https://github.com/meteor'
  twitter: '@meteor'
