# Theme defaults
# (available at theme.X. Note that config.X is also in there but theme wins, so it's not super useful)

logo:
  desktop: '../images/logo-coralspace.svg'
  mobile: '../images/logo.svg'

nav_links:
  'Meteor.com': 'https://www.meteor.com'
  'Install': 'https://www.meteor.com/install'
  'Guide': 'http://guide.meteor.com'
  'Tutorials': 'https://www.meteor.com/tutorials/blaze/creating-an-app'
  'Docs': 'http://docs.meteor.com'
  'Forums': 'https://forums.meteor.com/'
