favicon: '../images/favicon.png'

logo:
  nav_mobile: '../images/logo-coralspace-left.svg'
  url: 'http://www.meteor.com/developers'
  title: 'Meteor'
  subtitle: 'Developers'

nav_links:
  'Tutorials':
    url: http://www.meteor.com/tutorials
    target: _new
  'Guide':
    url: http://guide.meteor.com
    target: _new
  'API Docs':
    url: http://docs.meteor.com
    target: _new
  'Forums':
    url: https://forums.meteor.com/
    target: _new

social_links:
  github: 'https://github.com/meteor'
  twitter: '@meteor'